### ISSUE TITLE
The login button is no longer working

### ISSUE THREAD

**Issue by Ritakang0451** [prompt-engineering/chat-flow#10]
**Describe the bug**
The login button is no longer working

**To Reproduce**
I want to connect  to my ChatGPT account ,but the system doesn't respond when I paste the API address and click login.  
https://prompt.phodal.com/en-US/chatgpt/
![image](https://github.com/prompt-engineering/chat-flow/assets/43694785/f316269b-6e6e-4439-9de2-5822736a170e)

**Comment by phodal** [comment]
Ops, this project was not in maintance.
