### ISSUE TITLE
504 gpt-flow.vercel.app [POST] /api/chatgpt/chat/

### ISSUE THREAD

**Issue by lacusrinz** [prompt-engineering/chat-flow#5]
[软件系统设计]的step1 和 [模糊的需求到代码骨架]的step2执行就会报错
504 gpt-flow.vercel.app [POST] /api/chatgpt/chat/
[模糊的需求到代码骨架]的step1执行正常

上面步骤的内容直接贴到ChatGPT页面执行都是正常的

**Comment by phodal** [comment]
这个就比较恶心了，Vercel 服务器代理的时候 Timeout，要么就是本地自己直连过去：https://github.com/prompt-engineering/chat-visual-novel/blob/master/src/api/chat.ts
